services:
  player:
    build: ./player
    ports:
      - "50051:50051"
    volumes:
      - ./player:/player

  client:
    build: ./client
    ports:
      - "8080:8080"
    volumes:
      - ./client:/client
